version: "3"

services:
  server:
    build:
      context: ./server
    container_name: daekwang-server
    expose:
      - "8000"
    networks:
      - dkpc

  client:
    build:
      context: ./client
    container_name: daekwang-client
    expose:
      - "3000"
    networks:
      - dkpc
    env_file:
      - ./client/.env

  nginx:
    image: nginx:latest
    container_name: daekwang-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - server
    networks:
      - dkpc

networks:
  dkpc:
    driver: bridge
