version: "3"

services:
  server:
    build:
      context: ./server
    container_name: daekwang-server
    expose:
      - "8000"
    networks:
      - dkpc
    volumes:
      - ./server/firebase-key.json:/app/firebase-key.json
    environment:
      - ENV=${ENV}
      - FIREBASE_CREDENTIAL_PATH=${FIREBASE_CREDENTIAL_PATH}
      - INIT_ADMIN_USERNAME=${INIT_ADMIN_USERNAME}
      - INIT_ADMIN_PASSWORD=${INIT_ADMIN_PASSWORD}
      - ALLOWED_ADMIN_USERNAME=${ALLOWED_ADMIN_USERNAME}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}

  client:
    build:
      context: ./client
    container_name: daekwang-client
    expose:
      - "3000"
    networks:
      - dkpc
    environment:
      - KAKAO_API_KEY=${KAKAO_API_KEY}
      - NUXT_PUBLIC_API_URL=${NUXT_PUBLIC_API_URL}

  nginx:
    image: nginx:latest
    container_name: daekwang-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - server
    networks:
      - dkpc

networks:
  dkpc:
    driver: bridge
