
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AppAlert': typeof import("../components/AppAlert.vue")['default']
    'ConstructionCard': typeof import("../components/ConstructionCard.vue")['default']
    'Cursur': typeof import("../components/Cursur.vue")['default']
    'ShaderBackground': typeof import("../components/ShaderBackground.client.vue")['default']
    'CommonFooter': typeof import("../components/common/Footer.vue")['default']
    'CommonNavbar': typeof import("../components/common/Navbar.vue")['default']
    'CommonThemeToggle': typeof import("../components/common/ThemeToggle.vue")['default']
    'ModelPipeModel': typeof import("../components/model/PipeModel.vue")['default']
    'SceneCubeScene': typeof import("../components/scene/CubeScene.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'MdiIcon': typeof import("../node_modules/nuxt-mdi/dist/runtime/components/MdiIcon.vue")['default']
    'Align': typeof import("@tresjs/cientos")['Align']
    'AnimatedSprite': typeof import("@tresjs/cientos")['AnimatedSprite']
    'Backdrop': typeof import("@tresjs/cientos")['Backdrop']
    'BakeShadows': typeof import("@tresjs/cientos")['BakeShadows']
    'BaseCameraControls': typeof import("@tresjs/cientos")['BaseCameraControls']
    'Billboard': typeof import("@tresjs/cientos")['Billboard']
    'Box': typeof import("@tresjs/cientos")['Box']
    'CameraControls': typeof import("@tresjs/cientos")['CameraControls']
    'CatmullRomCurve3': typeof import("@tresjs/cientos")['CatmullRomCurve3']
    'Circle': typeof import("@tresjs/cientos")['Circle']
    'Cone': typeof import("@tresjs/cientos")['Cone']
    'ContactShadows': typeof import("@tresjs/cientos")['ContactShadows']
    'CubeCamera': typeof import("@tresjs/cientos")['CubeCamera']
    'CustomShaderMaterial': typeof import("@tresjs/cientos")['CustomShaderMaterial']
    'Cylinder': typeof import("@tresjs/cientos")['Cylinder']
    'Dodecahedron': typeof import("@tresjs/cientos")['Dodecahedron']
    'Edges': typeof import("@tresjs/cientos")['Edges']
    'Environment': typeof import("@tresjs/cientos")['Environment']
    'FBXModel': typeof import("@tresjs/cientos")['FBXModel']
    'Fbo': typeof import("@tresjs/cientos")['Fbo']
    'Fit': typeof import("@tresjs/cientos")['Fit']
    'GLTFModel': typeof import("@tresjs/cientos")['GLTFModel']
    'GlobalAudio': typeof import("@tresjs/cientos")['GlobalAudio']
    'GradientTexture': typeof import("@tresjs/cientos")['GradientTexture']
    'Grid': typeof import("@tresjs/cientos")['Grid']
    'HolographicMaterial': typeof import("@tresjs/cientos")['HolographicMaterial']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Icosahedron': typeof import("@tresjs/cientos")['Icosahedron']
    'Image': typeof import("@tresjs/cientos")['Image']
    'KeyboardControls': typeof import("@tresjs/cientos")['KeyboardControls']
    'Lensflare': typeof import("@tresjs/cientos")['Lensflare']
    'Levioso': typeof import("@tresjs/cientos")['Levioso']
    'Lightformer': typeof import("@tresjs/cientos")['Lightformer']
    'Line2': typeof import("@tresjs/cientos")['Line2']
    'MapControls': typeof import("@tresjs/cientos")['MapControls']
    'Mask': typeof import("@tresjs/cientos")['Mask']
    'MeshDiscardMaterial': typeof import("@tresjs/cientos")['MeshDiscardMaterial']
    'MeshGlassMaterial': typeof import("@tresjs/cientos")['MeshGlassMaterial']
    'MeshReflectionMaterial': typeof import("@tresjs/cientos")['MeshReflectionMaterial']
    'MeshWobbleMaterial': typeof import("@tresjs/cientos")['MeshWobbleMaterial']
    'MouseParallax': typeof import("@tresjs/cientos")['MouseParallax']
    'Ocean': typeof import("@tresjs/cientos")['Ocean']
    'Octahedron': typeof import("@tresjs/cientos")['Octahedron']
    'OrbitControls': typeof import("@tresjs/cientos")['OrbitControls']
    'Outline': typeof import("@tresjs/cientos")['Outline']
    'Plane': typeof import("@tresjs/cientos")['Plane']
    'PointerLockControls': typeof import("@tresjs/cientos")['PointerLockControls']
    'PositionalAudio': typeof import("@tresjs/cientos")['PositionalAudio']
    'Precipitation': typeof import("@tresjs/cientos")['Precipitation']
    'Reflector': typeof import("@tresjs/cientos")['Reflector']
    'Ring': typeof import("@tresjs/cientos")['Ring']
    'RoundedBox': typeof import("@tresjs/cientos")['RoundedBox']
    'SVG': typeof import("@tresjs/cientos")['SVG']
    'Sampler': typeof import("@tresjs/cientos")['Sampler']
    'ScreenSizer': typeof import("@tresjs/cientos")['ScreenSizer']
    'ScreenSpace': typeof import("@tresjs/cientos")['ScreenSpace']
    'ScrollControls': typeof import("@tresjs/cientos")['ScrollControls']
    'Sky': typeof import("@tresjs/cientos")['Sky']
    'Smoke': typeof import("@tresjs/cientos")['Smoke']
    'SoftShadows': typeof import("@tresjs/cientos")['SoftShadows']
    'Sparkles': typeof import("@tresjs/cientos")['Sparkles']
    'Sphere': typeof import("@tresjs/cientos")['Sphere']
    'Stars': typeof import("@tresjs/cientos")['Stars']
    'Stats': typeof import("@tresjs/cientos")['Stats']
    'StatsGl': typeof import("@tresjs/cientos")['StatsGl']
    'Superformula': typeof import("@tresjs/cientos")['Superformula']
    'Tetrahedron': typeof import("@tresjs/cientos")['Tetrahedron']
    'Text3D': typeof import("@tresjs/cientos")['Text3D']
    'Torus': typeof import("@tresjs/cientos")['Torus']
    'TorusKnot': typeof import("@tresjs/cientos")['TorusKnot']
    'TransformControls': typeof import("@tresjs/cientos")['TransformControls']
    'Tube': typeof import("@tresjs/cientos")['Tube']
    'TresCanvas': typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue")['default']
    'TresCanvas': IslandComponent<typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue")['default']>
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'ShaderBackground': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAppAlert': typeof import("../components/AppAlert.vue")['default']
    'LazyConstructionCard': typeof import("../components/ConstructionCard.vue")['default']
    'LazyCursur': typeof import("../components/Cursur.vue")['default']
    'LazyShaderBackground': typeof import("../components/ShaderBackground.client.vue")['default']
    'LazyCommonFooter': typeof import("../components/common/Footer.vue")['default']
    'LazyCommonNavbar': typeof import("../components/common/Navbar.vue")['default']
    'LazyCommonThemeToggle': typeof import("../components/common/ThemeToggle.vue")['default']
    'LazyModelPipeModel': typeof import("../components/model/PipeModel.vue")['default']
    'LazySceneCubeScene': typeof import("../components/scene/CubeScene.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyMdiIcon': typeof import("../node_modules/nuxt-mdi/dist/runtime/components/MdiIcon.vue")['default']
    'LazyAlign': typeof import("@tresjs/cientos")['Align']
    'LazyAnimatedSprite': typeof import("@tresjs/cientos")['AnimatedSprite']
    'LazyBackdrop': typeof import("@tresjs/cientos")['Backdrop']
    'LazyBakeShadows': typeof import("@tresjs/cientos")['BakeShadows']
    'LazyBaseCameraControls': typeof import("@tresjs/cientos")['BaseCameraControls']
    'LazyBillboard': typeof import("@tresjs/cientos")['Billboard']
    'LazyBox': typeof import("@tresjs/cientos")['Box']
    'LazyCameraControls': typeof import("@tresjs/cientos")['CameraControls']
    'LazyCatmullRomCurve3': typeof import("@tresjs/cientos")['CatmullRomCurve3']
    'LazyCircle': typeof import("@tresjs/cientos")['Circle']
    'LazyCone': typeof import("@tresjs/cientos")['Cone']
    'LazyContactShadows': typeof import("@tresjs/cientos")['ContactShadows']
    'LazyCubeCamera': typeof import("@tresjs/cientos")['CubeCamera']
    'LazyCustomShaderMaterial': typeof import("@tresjs/cientos")['CustomShaderMaterial']
    'LazyCylinder': typeof import("@tresjs/cientos")['Cylinder']
    'LazyDodecahedron': typeof import("@tresjs/cientos")['Dodecahedron']
    'LazyEdges': typeof import("@tresjs/cientos")['Edges']
    'LazyEnvironment': typeof import("@tresjs/cientos")['Environment']
    'LazyFBXModel': typeof import("@tresjs/cientos")['FBXModel']
    'LazyFbo': typeof import("@tresjs/cientos")['Fbo']
    'LazyFit': typeof import("@tresjs/cientos")['Fit']
    'LazyGLTFModel': typeof import("@tresjs/cientos")['GLTFModel']
    'LazyGlobalAudio': typeof import("@tresjs/cientos")['GlobalAudio']
    'LazyGradientTexture': typeof import("@tresjs/cientos")['GradientTexture']
    'LazyGrid': typeof import("@tresjs/cientos")['Grid']
    'LazyHolographicMaterial': typeof import("@tresjs/cientos")['HolographicMaterial']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyIcosahedron': typeof import("@tresjs/cientos")['Icosahedron']
    'LazyImage': typeof import("@tresjs/cientos")['Image']
    'LazyKeyboardControls': typeof import("@tresjs/cientos")['KeyboardControls']
    'LazyLensflare': typeof import("@tresjs/cientos")['Lensflare']
    'LazyLevioso': typeof import("@tresjs/cientos")['Levioso']
    'LazyLightformer': typeof import("@tresjs/cientos")['Lightformer']
    'LazyLine2': typeof import("@tresjs/cientos")['Line2']
    'LazyMapControls': typeof import("@tresjs/cientos")['MapControls']
    'LazyMask': typeof import("@tresjs/cientos")['Mask']
    'LazyMeshDiscardMaterial': typeof import("@tresjs/cientos")['MeshDiscardMaterial']
    'LazyMeshGlassMaterial': typeof import("@tresjs/cientos")['MeshGlassMaterial']
    'LazyMeshReflectionMaterial': typeof import("@tresjs/cientos")['MeshReflectionMaterial']
    'LazyMeshWobbleMaterial': typeof import("@tresjs/cientos")['MeshWobbleMaterial']
    'LazyMouseParallax': typeof import("@tresjs/cientos")['MouseParallax']
    'LazyOcean': typeof import("@tresjs/cientos")['Ocean']
    'LazyOctahedron': typeof import("@tresjs/cientos")['Octahedron']
    'LazyOrbitControls': typeof import("@tresjs/cientos")['OrbitControls']
    'LazyOutline': typeof import("@tresjs/cientos")['Outline']
    'LazyPlane': typeof import("@tresjs/cientos")['Plane']
    'LazyPointerLockControls': typeof import("@tresjs/cientos")['PointerLockControls']
    'LazyPositionalAudio': typeof import("@tresjs/cientos")['PositionalAudio']
    'LazyPrecipitation': typeof import("@tresjs/cientos")['Precipitation']
    'LazyReflector': typeof import("@tresjs/cientos")['Reflector']
    'LazyRing': typeof import("@tresjs/cientos")['Ring']
    'LazyRoundedBox': typeof import("@tresjs/cientos")['RoundedBox']
    'LazySVG': typeof import("@tresjs/cientos")['SVG']
    'LazySampler': typeof import("@tresjs/cientos")['Sampler']
    'LazyScreenSizer': typeof import("@tresjs/cientos")['ScreenSizer']
    'LazyScreenSpace': typeof import("@tresjs/cientos")['ScreenSpace']
    'LazyScrollControls': typeof import("@tresjs/cientos")['ScrollControls']
    'LazySky': typeof import("@tresjs/cientos")['Sky']
    'LazySmoke': typeof import("@tresjs/cientos")['Smoke']
    'LazySoftShadows': typeof import("@tresjs/cientos")['SoftShadows']
    'LazySparkles': typeof import("@tresjs/cientos")['Sparkles']
    'LazySphere': typeof import("@tresjs/cientos")['Sphere']
    'LazyStars': typeof import("@tresjs/cientos")['Stars']
    'LazyStats': typeof import("@tresjs/cientos")['Stats']
    'LazyStatsGl': typeof import("@tresjs/cientos")['StatsGl']
    'LazySuperformula': typeof import("@tresjs/cientos")['Superformula']
    'LazyTetrahedron': typeof import("@tresjs/cientos")['Tetrahedron']
    'LazyText3D': typeof import("@tresjs/cientos")['Text3D']
    'LazyTorus': typeof import("@tresjs/cientos")['Torus']
    'LazyTorusKnot': typeof import("@tresjs/cientos")['TorusKnot']
    'LazyTransformControls': typeof import("@tresjs/cientos")['TransformControls']
    'LazyTube': typeof import("@tresjs/cientos")['Tube']
    'LazyTresCanvas': typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue")['default']
    'LazyTresCanvas': IslandComponent<typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue")['default']>
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyShaderBackground': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AppAlert: typeof import("../components/AppAlert.vue")['default']
export const ConstructionCard: typeof import("../components/ConstructionCard.vue")['default']
export const Cursur: typeof import("../components/Cursur.vue")['default']
export const ShaderBackground: typeof import("../components/ShaderBackground.client.vue")['default']
export const CommonFooter: typeof import("../components/common/Footer.vue")['default']
export const CommonNavbar: typeof import("../components/common/Navbar.vue")['default']
export const CommonThemeToggle: typeof import("../components/common/ThemeToggle.vue")['default']
export const ModelPipeModel: typeof import("../components/model/PipeModel.vue")['default']
export const SceneCubeScene: typeof import("../components/scene/CubeScene.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const MdiIcon: typeof import("../node_modules/nuxt-mdi/dist/runtime/components/MdiIcon.vue")['default']
export const Align: typeof import("@tresjs/cientos")['Align']
export const AnimatedSprite: typeof import("@tresjs/cientos")['AnimatedSprite']
export const Backdrop: typeof import("@tresjs/cientos")['Backdrop']
export const BakeShadows: typeof import("@tresjs/cientos")['BakeShadows']
export const BaseCameraControls: typeof import("@tresjs/cientos")['BaseCameraControls']
export const Billboard: typeof import("@tresjs/cientos")['Billboard']
export const Box: typeof import("@tresjs/cientos")['Box']
export const CameraControls: typeof import("@tresjs/cientos")['CameraControls']
export const CatmullRomCurve3: typeof import("@tresjs/cientos")['CatmullRomCurve3']
export const Circle: typeof import("@tresjs/cientos")['Circle']
export const Cone: typeof import("@tresjs/cientos")['Cone']
export const ContactShadows: typeof import("@tresjs/cientos")['ContactShadows']
export const CubeCamera: typeof import("@tresjs/cientos")['CubeCamera']
export const CustomShaderMaterial: typeof import("@tresjs/cientos")['CustomShaderMaterial']
export const Cylinder: typeof import("@tresjs/cientos")['Cylinder']
export const Dodecahedron: typeof import("@tresjs/cientos")['Dodecahedron']
export const Edges: typeof import("@tresjs/cientos")['Edges']
export const Environment: typeof import("@tresjs/cientos")['Environment']
export const FBXModel: typeof import("@tresjs/cientos")['FBXModel']
export const Fbo: typeof import("@tresjs/cientos")['Fbo']
export const Fit: typeof import("@tresjs/cientos")['Fit']
export const GLTFModel: typeof import("@tresjs/cientos")['GLTFModel']
export const GlobalAudio: typeof import("@tresjs/cientos")['GlobalAudio']
export const GradientTexture: typeof import("@tresjs/cientos")['GradientTexture']
export const Grid: typeof import("@tresjs/cientos")['Grid']
export const HolographicMaterial: typeof import("@tresjs/cientos")['HolographicMaterial']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Icosahedron: typeof import("@tresjs/cientos")['Icosahedron']
export const Image: typeof import("@tresjs/cientos")['Image']
export const KeyboardControls: typeof import("@tresjs/cientos")['KeyboardControls']
export const Lensflare: typeof import("@tresjs/cientos")['Lensflare']
export const Levioso: typeof import("@tresjs/cientos")['Levioso']
export const Lightformer: typeof import("@tresjs/cientos")['Lightformer']
export const Line2: typeof import("@tresjs/cientos")['Line2']
export const MapControls: typeof import("@tresjs/cientos")['MapControls']
export const Mask: typeof import("@tresjs/cientos")['Mask']
export const MeshDiscardMaterial: typeof import("@tresjs/cientos")['MeshDiscardMaterial']
export const MeshGlassMaterial: typeof import("@tresjs/cientos")['MeshGlassMaterial']
export const MeshReflectionMaterial: typeof import("@tresjs/cientos")['MeshReflectionMaterial']
export const MeshWobbleMaterial: typeof import("@tresjs/cientos")['MeshWobbleMaterial']
export const MouseParallax: typeof import("@tresjs/cientos")['MouseParallax']
export const Ocean: typeof import("@tresjs/cientos")['Ocean']
export const Octahedron: typeof import("@tresjs/cientos")['Octahedron']
export const OrbitControls: typeof import("@tresjs/cientos")['OrbitControls']
export const Outline: typeof import("@tresjs/cientos")['Outline']
export const Plane: typeof import("@tresjs/cientos")['Plane']
export const PointerLockControls: typeof import("@tresjs/cientos")['PointerLockControls']
export const PositionalAudio: typeof import("@tresjs/cientos")['PositionalAudio']
export const Precipitation: typeof import("@tresjs/cientos")['Precipitation']
export const Reflector: typeof import("@tresjs/cientos")['Reflector']
export const Ring: typeof import("@tresjs/cientos")['Ring']
export const RoundedBox: typeof import("@tresjs/cientos")['RoundedBox']
export const SVG: typeof import("@tresjs/cientos")['SVG']
export const Sampler: typeof import("@tresjs/cientos")['Sampler']
export const ScreenSizer: typeof import("@tresjs/cientos")['ScreenSizer']
export const ScreenSpace: typeof import("@tresjs/cientos")['ScreenSpace']
export const ScrollControls: typeof import("@tresjs/cientos")['ScrollControls']
export const Sky: typeof import("@tresjs/cientos")['Sky']
export const Smoke: typeof import("@tresjs/cientos")['Smoke']
export const SoftShadows: typeof import("@tresjs/cientos")['SoftShadows']
export const Sparkles: typeof import("@tresjs/cientos")['Sparkles']
export const Sphere: typeof import("@tresjs/cientos")['Sphere']
export const Stars: typeof import("@tresjs/cientos")['Stars']
export const Stats: typeof import("@tresjs/cientos")['Stats']
export const StatsGl: typeof import("@tresjs/cientos")['StatsGl']
export const Superformula: typeof import("@tresjs/cientos")['Superformula']
export const Tetrahedron: typeof import("@tresjs/cientos")['Tetrahedron']
export const Text3D: typeof import("@tresjs/cientos")['Text3D']
export const Torus: typeof import("@tresjs/cientos")['Torus']
export const TorusKnot: typeof import("@tresjs/cientos")['TorusKnot']
export const TransformControls: typeof import("@tresjs/cientos")['TransformControls']
export const Tube: typeof import("@tresjs/cientos")['Tube']
export const TresCanvas: typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue")['default']
export const TresCanvas: IslandComponent<typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue")['default']>
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const ShaderBackground: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAppAlert: typeof import("../components/AppAlert.vue")['default']
export const LazyConstructionCard: typeof import("../components/ConstructionCard.vue")['default']
export const LazyCursur: typeof import("../components/Cursur.vue")['default']
export const LazyShaderBackground: typeof import("../components/ShaderBackground.client.vue")['default']
export const LazyCommonFooter: typeof import("../components/common/Footer.vue")['default']
export const LazyCommonNavbar: typeof import("../components/common/Navbar.vue")['default']
export const LazyCommonThemeToggle: typeof import("../components/common/ThemeToggle.vue")['default']
export const LazyModelPipeModel: typeof import("../components/model/PipeModel.vue")['default']
export const LazySceneCubeScene: typeof import("../components/scene/CubeScene.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyMdiIcon: typeof import("../node_modules/nuxt-mdi/dist/runtime/components/MdiIcon.vue")['default']
export const LazyAlign: typeof import("@tresjs/cientos")['Align']
export const LazyAnimatedSprite: typeof import("@tresjs/cientos")['AnimatedSprite']
export const LazyBackdrop: typeof import("@tresjs/cientos")['Backdrop']
export const LazyBakeShadows: typeof import("@tresjs/cientos")['BakeShadows']
export const LazyBaseCameraControls: typeof import("@tresjs/cientos")['BaseCameraControls']
export const LazyBillboard: typeof import("@tresjs/cientos")['Billboard']
export const LazyBox: typeof import("@tresjs/cientos")['Box']
export const LazyCameraControls: typeof import("@tresjs/cientos")['CameraControls']
export const LazyCatmullRomCurve3: typeof import("@tresjs/cientos")['CatmullRomCurve3']
export const LazyCircle: typeof import("@tresjs/cientos")['Circle']
export const LazyCone: typeof import("@tresjs/cientos")['Cone']
export const LazyContactShadows: typeof import("@tresjs/cientos")['ContactShadows']
export const LazyCubeCamera: typeof import("@tresjs/cientos")['CubeCamera']
export const LazyCustomShaderMaterial: typeof import("@tresjs/cientos")['CustomShaderMaterial']
export const LazyCylinder: typeof import("@tresjs/cientos")['Cylinder']
export const LazyDodecahedron: typeof import("@tresjs/cientos")['Dodecahedron']
export const LazyEdges: typeof import("@tresjs/cientos")['Edges']
export const LazyEnvironment: typeof import("@tresjs/cientos")['Environment']
export const LazyFBXModel: typeof import("@tresjs/cientos")['FBXModel']
export const LazyFbo: typeof import("@tresjs/cientos")['Fbo']
export const LazyFit: typeof import("@tresjs/cientos")['Fit']
export const LazyGLTFModel: typeof import("@tresjs/cientos")['GLTFModel']
export const LazyGlobalAudio: typeof import("@tresjs/cientos")['GlobalAudio']
export const LazyGradientTexture: typeof import("@tresjs/cientos")['GradientTexture']
export const LazyGrid: typeof import("@tresjs/cientos")['Grid']
export const LazyHolographicMaterial: typeof import("@tresjs/cientos")['HolographicMaterial']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyIcosahedron: typeof import("@tresjs/cientos")['Icosahedron']
export const LazyImage: typeof import("@tresjs/cientos")['Image']
export const LazyKeyboardControls: typeof import("@tresjs/cientos")['KeyboardControls']
export const LazyLensflare: typeof import("@tresjs/cientos")['Lensflare']
export const LazyLevioso: typeof import("@tresjs/cientos")['Levioso']
export const LazyLightformer: typeof import("@tresjs/cientos")['Lightformer']
export const LazyLine2: typeof import("@tresjs/cientos")['Line2']
export const LazyMapControls: typeof import("@tresjs/cientos")['MapControls']
export const LazyMask: typeof import("@tresjs/cientos")['Mask']
export const LazyMeshDiscardMaterial: typeof import("@tresjs/cientos")['MeshDiscardMaterial']
export const LazyMeshGlassMaterial: typeof import("@tresjs/cientos")['MeshGlassMaterial']
export const LazyMeshReflectionMaterial: typeof import("@tresjs/cientos")['MeshReflectionMaterial']
export const LazyMeshWobbleMaterial: typeof import("@tresjs/cientos")['MeshWobbleMaterial']
export const LazyMouseParallax: typeof import("@tresjs/cientos")['MouseParallax']
export const LazyOcean: typeof import("@tresjs/cientos")['Ocean']
export const LazyOctahedron: typeof import("@tresjs/cientos")['Octahedron']
export const LazyOrbitControls: typeof import("@tresjs/cientos")['OrbitControls']
export const LazyOutline: typeof import("@tresjs/cientos")['Outline']
export const LazyPlane: typeof import("@tresjs/cientos")['Plane']
export const LazyPointerLockControls: typeof import("@tresjs/cientos")['PointerLockControls']
export const LazyPositionalAudio: typeof import("@tresjs/cientos")['PositionalAudio']
export const LazyPrecipitation: typeof import("@tresjs/cientos")['Precipitation']
export const LazyReflector: typeof import("@tresjs/cientos")['Reflector']
export const LazyRing: typeof import("@tresjs/cientos")['Ring']
export const LazyRoundedBox: typeof import("@tresjs/cientos")['RoundedBox']
export const LazySVG: typeof import("@tresjs/cientos")['SVG']
export const LazySampler: typeof import("@tresjs/cientos")['Sampler']
export const LazyScreenSizer: typeof import("@tresjs/cientos")['ScreenSizer']
export const LazyScreenSpace: typeof import("@tresjs/cientos")['ScreenSpace']
export const LazyScrollControls: typeof import("@tresjs/cientos")['ScrollControls']
export const LazySky: typeof import("@tresjs/cientos")['Sky']
export const LazySmoke: typeof import("@tresjs/cientos")['Smoke']
export const LazySoftShadows: typeof import("@tresjs/cientos")['SoftShadows']
export const LazySparkles: typeof import("@tresjs/cientos")['Sparkles']
export const LazySphere: typeof import("@tresjs/cientos")['Sphere']
export const LazyStars: typeof import("@tresjs/cientos")['Stars']
export const LazyStats: typeof import("@tresjs/cientos")['Stats']
export const LazyStatsGl: typeof import("@tresjs/cientos")['StatsGl']
export const LazySuperformula: typeof import("@tresjs/cientos")['Superformula']
export const LazyTetrahedron: typeof import("@tresjs/cientos")['Tetrahedron']
export const LazyText3D: typeof import("@tresjs/cientos")['Text3D']
export const LazyTorus: typeof import("@tresjs/cientos")['Torus']
export const LazyTorusKnot: typeof import("@tresjs/cientos")['TorusKnot']
export const LazyTransformControls: typeof import("@tresjs/cientos")['TransformControls']
export const LazyTube: typeof import("@tresjs/cientos")['Tube']
export const LazyTresCanvas: typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue")['default']
export const LazyTresCanvas: IslandComponent<typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue")['default']>
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyShaderBackground: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
