// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025. 3. 30. 오후 11:18:29
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/qhfka/Desktop/project/daekwang/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/qhfka/Desktop/project/daekwang/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/qhfka/Desktop/project/daekwang/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/qhfka/Desktop/project/daekwang/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/qhfka/Desktop/project/daekwang/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/qhfka/Desktop/project/daekwang/plugins/**/*.{js,ts,mjs}","C:/Users/qhfka/Desktop/project/daekwang/composables/**/*.{js,ts,mjs}","C:/Users/qhfka/Desktop/project/daekwang/utils/**/*.{js,ts,mjs}","C:/Users/qhfka/Desktop/project/daekwang/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/qhfka/Desktop/project/daekwang/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/qhfka/Desktop/project/daekwang/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;