// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025. 4. 3. 오후 7:12:07
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/qhfka/Desktop/project/daekwang/client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/qhfka/Desktop/project/daekwang/client/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/qhfka/Desktop/project/daekwang/client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/qhfka/Desktop/project/daekwang/client/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/qhfka/Desktop/project/daekwang/client/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/qhfka/Desktop/project/daekwang/client/plugins/**/*.{js,ts,mjs}","C:/Users/qhfka/Desktop/project/daekwang/client/composables/**/*.{js,ts,mjs}","C:/Users/qhfka/Desktop/project/daekwang/client/utils/**/*.{js,ts,mjs}","C:/Users/qhfka/Desktop/project/daekwang/client/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/qhfka/Desktop/project/daekwang/client/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/qhfka/Desktop/project/daekwang/client/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;